manifest:
  remotes:
    - name: zmkrbitanga
      url-base: https://github.com/rbitanga
  projects:
    - name: zmk
      remote: zmkrbitanga
      revision: boot_protocol
      import: app/west.yml
  self:
    path: config
